version: '3.8'

services:
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    container_name: document_flow_fastapi_app
    restart: unless-stopped
    ports:
      - "8000:8000"
    volumes:
      - ./backend:/app
      - uploads_data:/app/uploads
    env_file:
      - ./backend/.env
    environment:
      UVICORN_HOST: "0.0.0.0"
      UVICORN_PORT: "8000"
      SECRET_KEY: "${SECRET_KEY}"

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile.frontend
    container_name: document_flow_frontend
    restart: unless-stopped
    ports:
      - "3000:3000"
    volumes:
      - ./frontend:/app
    stdin_open: true
    tty: true

volumes:
  uploads_data:
