version: '3.8'

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: document_flow_fastapi_app
    restart: unless-stopped
    ports:
      - "8000:8000"
    volumes:
      - .:/app
      - uploads_data:/app/uploads

    env_file:
      - .env
    environment:
      UVICORN_HOST: "0.0.0.0"
      UVICORN_PORT: "8000"
      SECRET_KEY: "${SECRET_KEY}"

volumes:
  uploads_data: